### ISSUE TITLE
ERROR: $log must be protected

### ISSUE THREAD

**Issue by minkbear** [dmitry-ivanov/laravel-console-logger#2] opened 2016-10-28 06:14 UTC
```
PHP Fatal error:  Access level to Illuminated\Console\ExceptionHandler::$log must be protected (as in class Illuminate\Foundation\Exceptions\Handler) or weaker
in C:\a\vendor\illuminated\console-logger\src\ExceptionHandler.php on line 8
PHP Fatal error:  Uncaught ReflectionException: Class Illuminated\Console\Except
ionHandler does not exist in C:\a\vendor\laravel\framework\src\Illuminate\Container\Container.
php:734
```

using laravel-console-logger version 1.1.7 and laravel 5.2.45 then I tried to change to `protected $log;` and run command again. It shows error below:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Illuminate\Foundation
\Exceptions\Handler::__construct() must implement interface Psr\Log\LoggerInterf
ace, instance of Illuminate\Foundation\Application given, called in C:\a\vendor\illuminated\co
nsole-logger\src\ExceptionHandler.php on line 17 and defined in C:\a\vendor\laravel\framework\
src\Illuminate\Foundation\Exceptions\Handler.php:43
```

Additional info when using version 1.0.12 the error has gone away.

Please advice.

Thanks you.

**Comment by dmitry-ivanov** [comment] 2016-10-28 13:38
Hi, @minkbear !

Thanks for issue, it was caused by Laravel 5.3 vs 5.2 incapabilities.
Fixed in 1.1.8 release. Please, update and try again.

Thank you!
Have a great day!

**Closed as completed by dmitry-ivanov** 2016-10-28 13:38 UTC

**Comment by dmitry-ivanov** [comment] 2016-10-31 10:29
@minkbear Can you plz confirm that problem was solved for you?

**Comment by minkbear** [comment] 2016-11-02 06:58
@dmitry-ivanov confirmed. It works fine on laravel 5.2 and console-logger 1.1.8

Thank you.
